version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: pdv
      POSTGRES_PASSWORD: pdv
      POSTGRES_DB: pdv_dev
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - "8080:8080"
volumes:
  db_data:
