# Cloud Run Service - Frontend
# Este arquivo define a configuração do serviço frontend no Cloud Run
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: bartab-frontend
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        # Scaling
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '10'
        
        # CPU é alocada apenas durante requests
        run.googleapis.com/cpu-throttling: 'true'
        
        # Timeout (mais baixo para frontend)
        run.googleapis.com/timeout-seconds: '60'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 60
      containers:
      - name: bartab-frontend
        image: gcr.io/PROJECT_ID/bartab-frontend:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: PORT
          value: '8080'
        resources:
          limits:
            cpu: '1000m'
            memory: '256Mi'
        # Health checks
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 0
          periodSeconds: 3
          timeoutSeconds: 3
          failureThreshold: 10
  traffic:
  - percent: 100
    latestRevision: true

